---

- hosts: all
  tasks:

  - name: install httpd package
    yum:		
      name: httpd
    when: ansible_distribution == "CentOS"      
  - name: install vim package
    yum: 	
      name: vim
    when: ansible_distribution == "CentOS"      
